services:
  frontend:
    build:
      context: "https://github.com/mkstowe/dashboard.git#:frontend"
      dockerfile: Dockerfile
    networks:
      - dashboard_net
    ports:
      - "4200:80"
    depends_on:
      - backend
    links:
      - backend

  backend:
    build:
      context: "https://github.com/mkstowe/dashboard.git#:backend"
      dockerfile: "Dockerfile"
    restart: always
    ports:
      - "3000:3000"
    networks:
      - dashboard_net

  proxy:
    image: nginx:stable-alpine
    environment:
      - NGINX_ENVSUBST_TEMPLATE_SUFFIX=.conf
      - NGINX_ENVSUBST_OUTPUT_DIR=/etc/nginx
    volumes:
      - ${PWD}/nginx.conf:/etc/nginx/templates/nginx.conf.conf
    ports:
      - 80:80
    networks:
      - dashboard_net

networks:
  dashboard_net:
