name: Build app and deploy to App Engine

on:
  push:
    branches: [main]

jobs:
  prepare:
    name: Initial setup
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        node-version: [20.x]

    steps:
      - uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Install dependencies
        run: yarn install
      - name: Google Cloud authentication
        uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: projects/144883645371/locations/global/workloadIdentityPools/my-pool/providers/my-provider
          service_account: github-actions@my-project.iam.gserviceaccount.com
    
  build-backend:
    name: Build backend
    runs-on: ubuntu-latest

    needs: [prepare]

    defaults:
      run:
        working-directory: ./backend

    strategy:
      matrix:
        node-version: [20.x]

    steps:
      - uses: actions/checkout@v4
      # - name: Setup Node
      #   uses: actions/setup-node@v4
      #   with:
      #     node-version: 20
      # - name: Install dependencies
      #   run: yarn install

  # build-frontend:
  #   name: Build frontend
  #   runs-on: ubuntu-latest
    
  #   defaults:
  #     run:
  #       working-directory: ./frontend

  #   strategy:
  #     matrix:
  #       node-version: [20.x]

  #   steps:
  #     - uses: actions/checkout@v4
  #     - run: ls
  #     - run: cat package.json
  #     - name: Setup Node
  #       uses: actions/setup-node@v4
  #       with:
  #         node-version: 20
  #     - name: Install dependencies
  #       run: yarn install
  #     - name: Build app
  #       run: yarn build-prod
    
      
  
