name: Build app and deploy to App Engine

on:
  push:
    branches: [main]
# on: workflow_dispatch

jobs:
  # prepare:
  #   name: Initial setup
  #   runs-on: ubuntu-latest

  #   permissions:
  #     contents: 'read'
  #     id-token: 'write'
    
  #   strategy:
  #     matrix:
  #       node-version: [20.x]

  #   steps:
  #     - name: Checkout 
  #       uses: actions/checkout@v4
  #     - name: Setup Node
  #       uses: actions/setup-node@v4
  #       with:
  #         node-version: 20
  #     - name: Install dependencies
  #       run: yarn install
          

  build-frontend:
    name: Build frontend
    runs-on: ubuntu-latest
    
    defaults:
      run:
        working-directory: ./frontend

    strategy:
      matrix:
        node-version: [20.x]

    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Install dependencies
        run: yarn install
      - name: Build app
        run: yarn build-prod
      - name: Upload dist
        uses: actions/upload-artifact@master
        with:
          name: dist
          path: ./frontend/dist/
    
  build-backend-and-deploy:
    name: Build backend and deploy to Google Cloud
    runs-on: ubuntu-latest

    needs: [build-frontend]

    # defaults:
      # run:
        # working-directory: ./backend

    strategy:
      matrix:
        node-version: [20.x]

    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
      - run: cd backend
      - name: Install backend dependencies
        run: yarn install
      - run: cd ..
      - name: Download frontend
        uses: actions/download-artifact@master
        with:
          name: dist
          path: ./frontend/dist
      - name: Deploy
        run: yarn deploy
