name: Build app and deploy to App Engine

on:
  push:
    branches: [main]

jobs:
  prepare:
    name: Prepare for builds
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20.x]
    
    steps:
      - uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Install dependencies
        run: yarn install
      - name: Generate frontend environment
        run: yarn env-prod
      - name: Upload artifact
        uses: actions/upload-artifact@master
        with:
          name: frontend-env
          path: frontend/src/environments/environment.production.ts

  build-backend:
    name: Build and deploy backend
    runs-on: ubuntu-latest

    needs: [prepare]

    defaults:
      run:
        working-directory: ./backend

    strategy:
      matrix:
        node-version: [20.x]

    steps:
      - uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Install dependencies
        run: yarn install

  build-frontend:
    name: Build and deploy frontend
    runs-on: ubuntu-latest

    needs: [prepare]
    
    defaults:
      run:
        working-directory: ./frontend

    strategy:
      matrix:
        node-version: [20.x]

    steps:
      - uses: actions/checkout@v4
      - run: cat package.json
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Install dependencies
        run: yarn install
      - name: Download artifact
        uses: actions/download-artifact@master
        with:
          name: frontend-env
          path: src/environments/environment.production.ts
      - name: Build app
        run: yarn build-prod
    
      
  
